import '../styles/globals.css';
import { Inter } from 'next/font/google';
import React from 'react';
import AppProvider from '../components/AppProvider';
import { Sidebar } from '../components/Sidebar/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next app',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="bg-grayishBlue">
      <body className={`${inter.className} flex flex-row justify-between w-full`}>
        <AppProvider>
          <Sidebar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
