name: Run CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI Pipeline
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${% raw %}{{secrets.GITHUB_TOKEN}}{% endraw %}" \
          --url https://api.github.com/repos/15-WG-Tron/pipelines/actions/workflows/ci-pipeline.yml/dispatches \
          -d '{"ref":"main"}'
