name: Run CI Pipeline

on:
  push:
    branches:
      - '*'
      
jobs:
  Trigger_Pipeline:
    permissions:
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CI Pipeline
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
          --url https://api.github.com/repos/15-WG-Tron/pipelines/actions/workflows/ci-pipeline.yml/dispatches \
          -d '{"ref":"main"}'
